# Generated by Django 4.0.3 on 2023-02-22 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abogado',
            options={},
        ),
        migrations.AlterField(
            model_name='abogado',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 14, 36, 22, 663509, tzinfo=utc), verbose_name='Fecha de publicaion '),
        ),
    ]
