# Generated by Django 4.0.3 on 2023-02-22 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0002_alter_abogado_options_alter_abogado_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 14, 39, 57, 917134, tzinfo=utc), verbose_name='Fecha de publicaion '),
        ),
    ]
