# Generated by Django 4.0.3 on 2023-02-23 02:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('abogados', '0003_alter_abogado_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 2, 4, 38, 573492, tzinfo=utc), verbose_name='Fecha de publicaion '),
        ),
    ]
