# Generated by Django 4.0.3 on 2023-02-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=200)),
                ('fecha_pub', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
